apiVersion: v1
kind: Service
metadata:
  name: ghostsvc
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
  clusterIP: 10.109.170.25
  selector:
    app: ghost

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost-con
        image: ghost:latest
        imagePullPolicy: Always
        env:
        - name:  NODE_ENV
          value: development
        - name: url
          value: http://10.225.150.105
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: 10.109.170.21
        - name: database__connection__user
          value: root
        - name: database__connection__password
          value: Password123
        - name: database__connection__database
          value: ghost-mysql
        ports:
        - containerPort: 2368
        readinessProbe:
          tcpSocket:
            port: 2368
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2368
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: ghost-volume
      
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-volume
  labels:
    type: ghost-volume
spec:
  storageClassName: local-path
  resources:
      requests:
        storage: 10Gi
  accessModes:
    - ReadWriteOnce
---








apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx-conf: |
    events {
      worker_connections  1024;
    }
    http {
      server {
          listen       2368;
          location / {
            proxy_pass http://10.109.170.25:2368;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
          - key: nginx-conf
            path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010
  selector:
    app: nginx
